### ISSUE TITLE
I'm getting this Error  

### ISSUE THREAD

**Issue by saleemmetallica** [WackyDawg/Tapswap--Bot#1]
==> Error performing actions on https://app.tapswap.club/?bot=app_bot_0#tgWebAppData=query_id%3DAAGEmNplAAAAAISY2mVAzhN3%26user%3D%257B%2522id%2522%253A1708824708%252C%2522first: TimeoutError: Waiting for selector `div#ex1-layer._tapContent_igohf_31 img` failed: Waiting failed: 60000ms exceeded
    at new WaitTask (D:\Documents\GitHub\Tapswap--Bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:50:34)
    at IsolatedWorld.waitForFunction (D:\Documents\GitHub\Tapswap--Bot\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Realm.js:25:26)
    at CSSQueryHandler.waitFor (D:\Documents\GitHub\Tapswap--Bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\QueryHandler.js:172:95)
    at async CdpFrame.waitForSelector (D:\Documents\GitHub\Tapswap--Bot\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:522:21)
    at async CdpPage.waitForSelector (D:\Documents\GitHub\Tapswap--Bot\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:1304:20)
    at async performActions (D:\Documents\GitHub\Tapswap--Bot\index.js:115:7)
    at async D:\Documents\GitHub\Tapswap--Bot\index.js:98:7
    at async Promise.all (index 1)
    at async D:\Documents\GitHub\Tapswap--Bot\index.js:93:3

**Comment by WackyDawg** [comment]
Check your URL  https://app.tapswap.club/?bot=app_bot_0#tgWebAppData=query_id%3DAAGEmNplAAAAAISY2mVAzhN3%26user%3D%257B%2522id%2522%253A1708824708%252C%2522first its not complete

**Comment by saleemmetallica** [comment]
Hey . Thank you for your response.. it's complete.. I delete the rest
before I post the issue 🙈🙈

**Comment by saleemmetallica** [comment]
I didn't want my tapswap link in public 🙈🙈

**Comment by WackyDawg** [comment]
OK i will look into the code and get back to you

**Comment by saleemmetallica** [comment]
Thank you brother 🙏🙏
